source 'https://github.com/CocoaPods/Specs.git'

workspace '../XNGAPIClient'
platform :ios, '7.0'
plugin 'slather'

target "Example" do
  pod 'XNGAPIClient', :path => '../XNGAPIClient.podspec'
  pod 'SAMKeychain', '~> 1.5.0'
end

target "ExampleTests" do
  pod 'Expecta'
  pod 'OHHTTPStubs', '= 3.1.0'
  pod 'OCMock'
end
